### ISSUE TITLE
获取网络时间，并不是网络时间

### ISSUE THREAD

**Issue by yoeaki** [ASkyBig/blog#16]
您好，我用您给的api，其实并不是网络时间，而是返回的本地时间戳。

**Comment by ASkyBig** [comment]
我把本地时间改成了昨天。**接口返回的不是本地时间戳** ，返回的是今天的时间。
![image](https://user-images.githubusercontent.com/26340566/88754890-71a09080-d192-11ea-8b93-73c845fe682a.png)
